chore: Improve cypress tests (STARGATE-2058)
AptoPayments/apto-pci-sdk-web pull request #13
Opened 2020-12-01 01:42 UTC by lukewhyte

2020-12-01 07:01 UTC, IagoLast approved these changes
Just a few nits (🌈 )  but LGTM 🚀

2020-12-01 07:01 UTC, IagoLast commented on cypress/integration/pci-sdk-web.spec.js
> +		it('should allow user to specify target element for iframe', () => {
🌈 This description wasn't clean for me

2020-12-01 07:01 UTC, IagoLast commented on cypress/integration/pci-sdk-web.spec.js
> +	describe('AptoPCISdk.init', () => {
🌈  I don't think we need to specify AptoPCISdk since is defined on top level describe

2020-12-01 07:01 UTC, IagoLast commented on cypress/integration/pci-sdk-web.spec.js
> +		it('should display the data when showPCIData is called with a known cardholder id', () => {
🌈  when the client is PCI compliant?

2020-12-01 07:01 UTC, IagoLast commented on cypress/integration/pci-sdk-web.spec.js
> +					.then(AptoPCISdk.showPCIData);
🌈 I think this might be on a different line to differentiate the 3 steps (Arrange Act Assert)

2020-12-01 07:01 UTC, IagoLast commented on cypress/support/commands/stubJSONResponses.js
> +Cypress.Commands.add('stubJSONResponse', stubJSONResponse);
✨

2020-12-01 07:01 UTC, IagoLast commented on cypress/support/commands/stubPrompt.js
> +Cypress.Commands.add('stubPrompt', stubPrompt);
🌈 stubWindowPromptValue or something similar sounds clearer to me

2020-12-01 07:07 UTC, IagoLast requested changes
@lukewhyte just realised your format is not prettier compatible. Please enable prettier and fix files first

2020-12-01 14:35 UTC, alejandraarri approved these changes

2020-12-02 04:41 UTC, lukewhyte commented
> @lukewhyte just realised your format is not prettier compatible. Please enable prettier and fix files first

@IagoLast I ran it from the command line but it is worth noting that the `cypress` directory is not covered by `editor.formatOnSave`. Not sure if we want to change that

2020-12-02 07:52 UTC, merged