feat: Add option to easily display card-network (ACQ-2132)
AptoPayments/apto-pci-sdk-web pull request #72
Opened 2021-10-20 10:18 UTC by alejandraarri

2021-10-20 11:30 UTC, alejandraarri commented
I'm currently working on the size option.

2021-10-20 14:42 UTC, IagoLast commented on packages/pci-sdk-iframe/src/pages/app/CardData.test.tsx
> +}
🌈  should we move this to a test utils folder?

2021-10-20 14:47 UTC, IagoLast requested changes
LGTM some minor changes

2021-10-20 14:47 UTC, IagoLast commented on packages/pci-sdk-iframe/src/pages/app/components/CardData/CardData.css
> +}
🌈  I like to have this stuff at the bottom of the file

2021-10-20 14:47 UTC, IagoLast commented on packages/pci-sdk-iframe/src/types/IApplicationState.d.ts
> +	networkLogoSymbol: string;
Lets create types with all the possible values .

2021-10-20 14:47 UTC, IagoLast commented on packages/pci-sdk-iframe/src/types/IConfigOptions.d.ts
> +	networkLogoSymbol: string;
Lets create types with all the possible values .

2021-10-20 14:47 UTC, IagoLast commented on packages/pci-sdk-iframe/src/pages/app/CardData.test.tsx
> +				symbol: 'Visa-blue',
Is this right? should't Visa be lowercase?

2021-10-20 14:47 UTC, IagoLast commented on packages/pci-sdk-iframe/src/pages/app/CardData.test.tsx
> +				symbol: 'Visa-blue',
actually why is the test working ?! 🤔

2021-10-20 14:47 UTC, IagoLast commented on packages/pci-sdk-web/src/index.ts
> +	theme?: string,
Theme is not any string is an enum `light` or `dark` .

I found a bug yesterday because this should be initialised to one of those values not `1`

2021-10-21 10:22 UTC, alejandraarri commented on packages/pci-sdk-iframe/src/pages/app/CardData.test.tsx
> +}
Given that we are going to organize the tests in a separate ticket, shouldn't we do this at that moment?

2021-10-21 14:52 UTC, IagoLast approved these changes

2021-10-21 15:38 UTC, merged