feat: customize messages displayed to the user (STARGATE-1732)
AptoPayments/apto-pci-sdk-web pull request #9
Opened 2020-11-20 13:41 UTC by lukewhyte

2020-11-20 13:49 UTC, IagoLast reviewed
LGTM just one question: are we leaving the public API for a different PR?

2020-11-20 13:49 UTC, IagoLast commented on packages/pci-sdk-iframe/src/pages/app/App.test.tsx
> +				await waitFor(() => expect(window.alert).toHaveBeenCalledWith('custom_tooManyAttemptsMessage'));
we do only care of 2 out 4 error messages? :trollface:

2020-11-20 13:49 UTC, IagoLast commented on packages/pci-sdk-iframe/src/pages/app/useApp.ts
> +		failed2FAPrompt: urlParams.get('failed2FAPrompt') as string || 'Wrong code. try again:',
🌈 maybe defaults should be constants

2020-11-20 13:52 UTC, lukewhyte commented
> LGTM just one question: are we leaving the public API for a different PR?

I can add it to this PR

2020-11-21 09:32 UTC, IagoLast requested changes
- Missing test cases
- Lint error

2020-11-21 09:32 UTC, IagoLast commented
> > LGTM just one question: are we leaving the public API for a different PR?
> 
> I can add it to this PR

Nah, its ok like this

2020-11-23 13:25 UTC, lukewhyte commented
> * Missing test cases
> * Lint error

Lint error is fixed. Adding the missing test cases is a larger conversation. They're used in window.prompt, which is not supported by JSDOM. Thus, we'd have to build our own version of prompt (_[I ran across an old demo of such while investigating this](https://gist.github.com/apeckham/404170)_) and test our error messages in that context.

2020-11-23 14:31 UTC, IagoLast reviewed
I was thinking about this and I'm not sure if we want to persist those messages in the state...
I think it complicates the logic and we know it's not going to change (we don't have any methods for that).

Also I've working on a refactor that I want to discuss with you first

2020-11-24 17:33 UTC, IagoLast approved these changes

2020-11-24 17:35 UTC, merged